### PR TITLE
Add support for secrets.json

### LINKED ISSUE #371: triggerUri exposes plain text Blue Iris Username and Password
**Is your feature request related to a problem? Please describe.**
When adding a `triggerUri` for a Blue Iris system that requires authentication, my `user` and `pw` are in a file in plain text.

**Describe the solution you'd like**
Preferably this would be a secret, environment variable, or in a file of key/value pairs that get's ignored when a user backs up their configuration (similar to home assistant: https://www.home-assistant.io/docs/configuration/secrets/). 

The best solution in my mind would be to take mustache templating further. For example in the docs there is: 
```
"http://192.168.1.100:81/admin?trigger&camera=FrontDoorHD&user=username&pw=password"
```
 This could become:
```
"http://192.168.1.100:81/admin?trigger&camera=FrontDoorHD&user={blueIris.username}&pw={blueIris.password}"
```
This could look inside `settings.json`. Then alternatively `settings.json` could use mustache templating to look to an environment variable or secret or key/value pair file; which would be a benefit to all the other settings that have a username/password. Then the mustache templating in `triggerUri` could consistently look to `settings.json`. Something like:
```
{
  "blueIris": {
    "username": "{ENV.BLUE_IRIS_USERNAME}",
    "password": "{ENV.BLUE_IRIS_PASSWORD}"
  }
}
```

...or possibly `SECRET.BLUE_IRIS_PASSWORD` or something along those lines.

**Describe alternatives you've considered**
I described a couple alternatives above.

**Additional context**
I think the main problem here is the need to separate configuration from secrets. If my server dies, how do I get my configuration back to get up and running again; ideally it's backed up, but it shouldn't be backed up with plain text secrets. With my other docker containers I have written a shell script that grabs usernames/passwords from LastPass using their cli and then uses `sed` to drop them in `.env` files and then I reference those `.env` files in my `docker-compose` (https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option).

ALSO, I love node/typescript and can probably provide some assistance in this implementation.

ALSO ALSO, thanks to everyone that has contributed to this project. I absolutely love it!

### PR DESCRIPTION
**Pull request by danecreekphotography**
# Fixes #371

## Description of changes

Adds support for `secrets.json` and mustache template insertion into `settings.json` and `triggers.json`.

## Checklist

If your change touches anything under src or the README.md file
these items must be done:

- [X] User-facing change description added to unreleased section of CHANGELOG.md

### CODE REVIEW

**Comment by danecreekphotography** [comment]
@TonyBrobston Can you please pull the latest issue371 and make sure it still works as expected? I released v5.4.0 with support for the new `activateRegions` feature and then rebased this branch to pull those changes in. If it looks good on your end this will go out as v5.5.0.

**Comment by TonyBrobston** [comment]
@danecreekphotography I just pulled the latest and am running. Prior to this pull things have been working great. I'll try to update you later today on how the latest is working.

**Comment by TonyBrobston** [comment]
@danecreekphotography Looks good to me. Everything seems to be working for me.

**Comment by danecreekphotography** [comment]
Ok great, I'll try pushing this to release later tonight!

**Pull request merged**
