### PR TITLE
Replace try/catch with .catch()

### LINKED ISSUE #68: Replace some try/catch blocks with .catch()
There are quite a few places in the code where try/catch blocks with `let` variables just outside the try statement can be replaced with the cleaner `.catch()` method for handling errors.

### PR DESCRIPTION
**Pull request by mattbho**
# Fixes #68

## Description of changes
Replaced try/catch blocks with cleaner .catch()
## Checklist

If your change touches anything under src or the README.md file
these items must be done:

- [x] CHANGELOG.md updated
- [x] `npm version` run

### CODE REVIEW

**Comment by danecreekphotography** [comment]
Oooh nice, thank you. I'll look later tonight or tomorrow morning and take it for a spin.

It's times like these I wish I had test automation. I guess that's another task for the issues list...

Question for you: what was your dev environment? Did you try the Dev - Containers stuff at all?

**Comment by mattbho** [comment]
> Oooh nice, thank you. I'll look later tonight or tomorrow morning and take it for a spin.
> 
> It's times like these I wish I had test automation. I guess that's another task for the issues list...
> 
> Question for you: what was your dev environment? Did you try the Dev - Containers stuff at all?

Oh shoot, I forgot about your message on the issue. I just ran `npm version minor` and it seemed to work. That may have not been the correct command? I'll run the command on the issue comments locally and see if anything changes

**Comment by danecreekphotography** [comment]
It would have thrown an error if it didn't work and bailed out.

**Comment by mattbho** [comment]
> It would have thrown an error if it didn't work and bailed
Let me reopen this PR, I think I may have messed up some git tagging since this is my first time running a npm version command. But to answer your question, yes I'm in a dev container.

**Comment by danecreekphotography** [comment]
Looks nice. The change in TriggerManager.ts:37 is exactly what prompted me to log this issue. Never did like having to declare the variable outside the try/catch just to make sure it exists.

Looks like there's still three try/catches left in the code:

https://github.com/danecreekphotography/node-deepstackai-trigger/blob/ccb9488ca22cdb85d452bb39af3112894778f2a3/src/main.ts#L37

I think this one can just stay as-is since it's the catch all wrapping the entire app.

https://github.com/danecreekphotography/node-deepstackai-trigger/blob/ccb9488ca22cdb85d452bb39af3112894778f2a3/src/Trigger.ts#L223

https://github.com/danecreekphotography/node-deepstackai-trigger/blob/ccb9488ca22cdb85d452bb39af3112894778f2a3/src/Trigger.ts#L239

These two can also change to the `.catch()` pattern with the successful log message getting sent at the end of the function. When you re-open the PR include those two as well.

**Comment by danecreekphotography** [comment]
I feel your pain and thanks for being the test subject for `npm version`. I tried it this morning too and it was pretty awful. I think I'm going to get rid of that and just say "edit the version in package.json" and "run npm:lint" (or something similar) since that's what npm version does without all the nonsense of npm version...

**Comment by danecreekphotography** [comment]
Also I got rid of the git tag part of the npm version script since it was too dangerous and causing me grief. I don't think you did any git tags that I can see. Tags are now manually done by me when I manually push a release out with the git releases tab.

**Pull request closed without merging**
